name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: marketplace_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm test
      - name: Verify OpenAPI spec is up-to-date
        run: |
          pnpm generate:spec
          git diff --exit-code openapi.yaml
